name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod
          - all
      beta:
        required: false
        type: boolean
        description: deploy beta version on AKS
        default: false

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Select the Environment
      beta:
        required: false
        type: boolean
        description: deploy beta version on AKS
        default: false
    secrets:
      bot_token_github:
        required: true

env:
  NAMESPACE: apiconfig
  APP_NAME: pagopaapiconfig


permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    strategy:
      matrix:
        environment: [ dev, uat, prod ]
        include:
          - environment : dev
            short: d
          - environment : uat
            short: u
          - environment : prod
            short: p
    uses: ./.github/workflows/self_hosted.yml
    with:
      environment: ${{ inputs.environment }}
      matrix: ${{ matrix.environment }}
      beta: ${{ inputs.beta }}
    secrets:
      token: ${{secrets.BOT_TOKEN_GITHUB}}
