name: Integration Tests

on:
  pull_request:
    brances: [main]
  merge_group:
    types: [checks_requested]
    branches: [main]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Dump GitHub context
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

      - name: PR is Ready to merge
        run: exit 1
        if: ${{github.event_name != 'merge_group'}}

      - name: Run Integration Tests
        run: |
          cd ./integration-test
          sh run_integration_test.sh dev
