name: Release

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      semver:
        required: true
        type: choice
        description: Select the new Semantic Version
        options:
          - major
          - minor
          - patch
          - buildNumber
          - skip

  workflow_call:
    inputs:
      semver:
        required: true
        type: string
        description: Select the new Semantic Version
    secrets:
      bot_token_github:
        required: true


permissions:
  packages: write
  contents: write
  issues: write
  id-token: write
  actions: read


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  release:
    name: Create a New Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
    steps:
      - name: Dump GitHub context
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}

      - name: Make Release
        id: release
        uses: pagopa/github-actions-template/maven-release@deploy_aks_beta
        with:
          semver: ${{inputs.semver}}
          github_token: ${{ secrets.BOT_TOKEN_GITHUB }}

  image:
    needs: [release]
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ !(inputs.semver == 'skip') }}
    steps:
      - name: Build and Push
        id: semver
        uses: pagopa/github-actions-template/ghcr-build-push@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name}}
          tag: ${{ needs.release.outputs.version }}
